import { env } from "@/lib/env";
import type { CategoryNode, MediaItem } from "@/types/domain";

const now = new Date().toISOString();

export const demoCategories: CategoryNode[] = [
  {
    id: "root-1",
    eventSlug: env.DEFAULT_EVENT_SLUG,
    parentId: null,
    name: "제16기 한몽 청년수련회",
    slug: "16th-hanmong-retreat",
    description: "루트 카테고리",
    coverMediaId: null,
    sortOrder: 0,
    depth: 0,
    path: "/16th-hanmong-retreat",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "day-1",
    eventSlug: env.DEFAULT_EVENT_SLUG,
    parentId: "root-1",
    name: "1일차",
    slug: "day-1",
    description: null,
    coverMediaId: null,
    sortOrder: 1,
    depth: 1,
    path: "/16th-hanmong-retreat/day-1",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "day-2",
    eventSlug: env.DEFAULT_EVENT_SLUG,
    parentId: "root-1",
    name: "2일차",
    slug: "day-2",
    description: null,
    coverMediaId: null,
    sortOrder: 2,
    depth: 1,
    path: "/16th-hanmong-retreat/day-2",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "culture-exchange",
    eventSlug: env.DEFAULT_EVENT_SLUG,
    parentId: "day-2",
    name: "문화교류",
    slug: "culture-exchange",
    description: null,
    coverMediaId: null,
    sortOrder: 1,
    depth: 2,
    path: "/16th-hanmong-retreat/day-2/culture-exchange",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "praise-night",
    eventSlug: env.DEFAULT_EVENT_SLUG,
    parentId: "day-2",
    name: "찬양집회",
    slug: "praise-night",
    description: null,
    coverMediaId: null,
    sortOrder: 2,
    depth: 2,
    path: "/16th-hanmong-retreat/day-2/praise-night",
    createdAt: now,
    updatedAt: now,
  },
];

export const demoMedia: MediaItem[] = [
  {
    id: "media-1",
    eventSlug: env.DEFAULT_EVENT_SLUG,
    categoryId: "culture-exchange",
    mediaType: "image",
    title: "몽골 공연 준비",
    description: "무대 리허설 장면",
    originalFilename: "mongol-performance.jpg",
    originalExtension: "jpg",
    mimeType: "image/jpeg",
    fileSize: 2480000,
    checksum: null,
    width: 2048,
    height: 1365,
    durationSeconds: null,
    originalS3Key: null,
    previewS3Key: null,
    thumbnailS3Key: null,
    posterS3Key: null,
    status: "ready",
    uploadSessionId: null,
    capturedAt: now,
    createdAt: now,
    updatedAt: now,
    deletedAt: null,
  },
  {
    id: "media-2",
    eventSlug: env.DEFAULT_EVENT_SLUG,
    categoryId: "praise-night",
    mediaType: "video",
    title: "찬양집회 하이라이트",
    description: "현장 영상",
    originalFilename: "praise-night.mp4",
    originalExtension: "mp4",
    mimeType: "video/mp4",
    fileSize: 180240000,
    checksum: null,
    width: 1920,
    height: 1080,
    durationSeconds: 92,
    originalS3Key: null,
    previewS3Key: null,
    thumbnailS3Key: null,
    posterS3Key: null,
    status: "ready",
    uploadSessionId: null,
    capturedAt: now,
    createdAt: now,
    updatedAt: now,
    deletedAt: null,
  },
  {
    id: "media-3",
    eventSlug: env.DEFAULT_EVENT_SLUG,
    categoryId: "day-1",
    mediaType: "image",
    title: "출발 전 단체 사진",
    description: null,
    originalFilename: "group-photo.webp",
    originalExtension: "webp",
    mimeType: "image/webp",
    fileSize: 1240000,
    checksum: null,
    width: 1600,
    height: 1200,
    durationSeconds: null,
    originalS3Key: null,
    previewS3Key: null,
    thumbnailS3Key: null,
    posterS3Key: null,
    status: "ready",
    uploadSessionId: null,
    capturedAt: now,
    createdAt: now,
    updatedAt: now,
    deletedAt: null,
  },
];
